### PR TITLE
Update photon.py

### PR DESCRIPTION
**Pull request by neutrinoguy**
**urllib3** shows ssl warnings during execution. Ignored that using warning module for clear execution of script.

### CODE REVIEW

**Comment by s0md3v** [comment]
Photon already handles such warnings. Take a look [here](https://github.com/s0md3v/Photon/blob/32f5c3f72ca807b47111aff4e76e21c17f56b7d4/photon.py#L49)

Can you show me a screenshot?

**Comment by neutrinoguy** [comment]
Here it is:

image

Take a look @s0md3v

**Comment by s0md3v** [comment]
Hi there!

Thanks for contributing to Photon.
Can you please re-clone and see if the problem still exists?
Your patch isn't that elegant. I used this instead:
`urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)`

**Comment by neutrinoguy** [comment]
Hi there!

I did the clone again from scratch but the issue still persists. I guess `warnings.filterwarnings()` should be used !

**Pull request merged**
