### PR TITLE
Improve dev-experience

### PR DESCRIPTION
**Pull request by dgarana**
Add .gitignore and requirements file just to improve development experience.

Doing this:
- You won't need to remove unnecessary python compiled files or either other not needed files.
- You just "pip install -r requirements.txt", and you'll have all necessary third-party libraries to execute script.

### CODE REVIEW

**Comment by s0md3v** [comment]
Adding a new dependency `six`, just to avoid use of an try and except block is a terrible idea.

**Comment by dgarana** [comment]
Forget about the last commit, it should be on another branch.
Regarding to #!python, it should be /usr/bin/python instead, which uses the python installed on the system, also it has no +x property, so it's not executable, so #! is useless.

**Comment by dgarana** [comment]
I do know how shebangs work. Just note that I've removed the commit related to it.

Also, I don't understand why you're using a shebang when you're forcing the python interpreter on the command line.

**Comment by s0md3v** [comment]
Because I don't have python2 installed at that machine :D

**Pull request closed without merging**
