### PR TITLE
handling fld extract with tld

### PR DESCRIPTION
**Pull request by yeahdef**
this should fix image resolution using an argument like `-u "https://www.levis.com"`

### CODE REVIEW

**Comment by s0md3v** [comment]
There's something wrong with your code as the tests have failed.

I don't know what are you trying to do here.
Do you want to check if the image doesn't exist? Well in that case we can just skip saving the image instead of doing "things" you are trying to do.

**Comment by yeahdef** [comment]
the dnsdumpster plugin does not test if the image responds 200, and was writing html 404 response content into the image file.

**Comment by yeahdef** [comment]
It's tough to determine proper TLD without some special handling.
consider 1. `https://www.amazon.co.uk/` vs 2. `https://beta.alpha.foo.com/`.
is the top level domain of 1. `uk` or `co.uk`?
how do we know the TLD of 2. is not `foo.com`?
the TLD library helps us parse these domains into objects where we can extract the known TLD, FLD, etc.

**Comment by s0md3v** [comment]
It makes sense now.

Thanks for contributing :heart:

**Pull request merged**
