### PR TITLE
Option to skip crawling of URLs that match a regex pattern

### PR DESCRIPTION
**Pull request by ConnorSkees**
Added option to skip crawling of URLs that match a regex pattern, changed handling of seeds, and removed double spaces.

I am assuming this is what you meant in the ideas column tell me if I'm way off though :)

### CODE REVIEW

**Comment by s0md3v** [comment]
Thanks for fixing all that stuff :heart:

I will merge the pull request as soon as I finish evaluating and testing the code.

**Comment by s0md3v** [comment]
`is_link()` function accepts a string as an argument i.e. a single URL.
While your `parse()` function accepts a list of URLs.
But what's the point of accepting a list when you have only a single URL available inside the `is_link()` function?

**Comment by ConnorSkees** [comment]
There isn't really a point in having it accept a list of urls. I originally wrote the function thinking it would be called on `storage` before the links in `storage` were crawled. I instead used it with `is_link()` and did not edit the function.

**Comment by s0md3v** [comment]
How about this?
I guess this is more efficient :)

**Comment by ConnorSkees** [comment]
Is there a reason to use a regex for finding `a` tags over bs4?

**Comment by s0md3v** [comment]
bs64 is slower.

**Comment by s0md3v** [comment]
It's not working as intended, can you please check what's wrong?

**Comment by ConnorSkees** [comment]
It was adding urls from zap. Now, doing -- exclude .* gives 

URLs retrieved from robots.txt: 0
 Level 1: 1 URLs
 Progress: 1/1
 Crawling 15 JavaScript files
 Progress: 15/15
--------------------------------------------------
 URLs: 1
 Intel: 0
 Files: 0
 Endpoints: 0
 Fuzzable URLs: 0
 Custom strings: 0
 JavaScript Files: 15
 External References: 0
--------------------------------------------------

**Comment by s0md3v** [comment]
It just doesn't work!

screenshot_2018-08-01_23-54-44
screenshot_2018-08-01_23-54-56

**Comment by s0md3v** [comment]
It doesn't seem to work :/

screenshot_2018-08-01_23-58-16

**Comment by ConnorSkees** [comment]
The flag for the exclusion regex is --exclude. Does changing it to that change the result?

**Comment by s0md3v** [comment]
It's confusing!
It's working perfecting with the real stackoverflow.
Thanks for everything.
I will merge it in 5.

**Comment by s0md3v** [comment]
Alright, I found the bug. It doesn't work if the website doesn't have a sitemap.xml or robots.txt

screenshot_2018-08-02_00-04-34

**Comment by s0md3v** [comment]
Checking every URL against the regex is a bad idea because it will reduce performance.
Can't you implement in `extractor` where links are returned so we can quickly return the ones which don't match?

**Comment by s0md3v** [comment]
I have one more change to make but I will make it myself because I have bothered you enough already.
Thanks for everything bro :heart: 
You rock!

**Comment by ConnorSkees** [comment]
sorry, just wondering what about the excluding feature was poorly implemented (for my own reference)

**Comment by s0md3v** [comment]
I suggested that checking URLs one by one is slow and that's why I asked you to move it from `is_link()` to `extractor` but you still put it in a place where the URLs will be checked one by i.e. in a `for` loop.

I didn't want to bother you anymore & it would have been unfair if I didn't merge your request after this much of hard work so I kept the re-factor and merged it.

However, I have now realized the best place to to exclude the URLs is [this](https://github.com/s0md3v/Photon/blob/147a0fa8ab0b58f425a4ff3086146815b37e012c/photon.py#L399).

**Comment by ConnorSkees** [comment]
I'm really interested now- how can you exclude the urls matching the regex without checking them all one by one?

It's totally fine bothering me :) this is a great learning experience

**Comment by s0md3v** [comment]
It's not really about matching them, it's about the optimal location.
If you match them while http requests are being made, you will end up eating **their** time.
That's why I suggested another location in the previous comment.

**Pull request merged**
