### PR TITLE
Added -v/--verbose option + fixed few logic error in detecting bad js files

### PR DESCRIPTION
**Pull request by theInfectedDrake**
Changes:
- Added the `-v/--verbose` option for verbose output.
- Fixed 2 logical errors in detecting bad JS scripts.
        - With this fix, number of bad js files have almost gone to zero.

### CODE REVIEW

**Comment by s0md3v** [comment]
Thanks for contributing to Photon.
The build has failed due to inconsistent use of tabs and spaces.
Please convert the indentation to spaces to fix the issue.

**Comment by theInfectedDrake** [comment]
Ah fixed the indentation error causing the build to fail. Python 3 indentation errors drives me crazy and are nightmares. Thats why I go with Python2. :(

**Comment by theInfectedDrake** [comment]
Hell yeah, fixed it. 🌭✍💥

**Comment by s0md3v** [comment]
> Thats why I go with Python2. :(

Python2 will be deprecated [real soon](https://pythonclock.org/).

**Comment by s0md3v** [comment]
I just reviewed your PR and we need to work on a couple of things before I can merge it.

- [ ] Remove all the comments you added, most of them are misleading or not helpful at all.
- [ ] Revert the changes you made to colors and lables
- [ ] Progress display isn't showing at all in python2 and prints in separate lines in python3

**Comment by theInfectedDrake** [comment]
Well,
1. I never touched the progress bar area. I don't understand why its happening. I will still have a look.
2. Indentation, I have no control over it. Consider fixing it yourself since you have seen how miserable my indentation is.
3. When I issued the last commit, there was no conflict. You habe modified the code meanwhile (which was not at all a sane idea) and hence the conflict.
4. Comments part, I'll do it (only after you fix the conflicts).
5. About the color coding, color reset is `\033[0m` and not `\033[1;m`. Have a [look](https://gist.github.com/vratiu/9780109).

**Comment by theInfectedDrake** [comment]
About the colors part, I did a bit of research and finally got that `\033[0m` actually resets the color totally (style+color). `\033[0m` is equivalent to `\033[m` and `\033[1m` is for bold. So as per your saying when you are doing `\033[1;m` to reset colors, you are basically converting the text first to bold and then resetting it back to normal since `\033[1;m` is equivalent to doing `\033[1m + \033[0m`. I hope it makes some sense.

**Comment by s0md3v** [comment]
Animation isn't' working in python2.

**Comment by theInfectedDrake** [comment]
:') I think it shouldn't matter when you said this. 
> Python2 will be deprecated real soon.

Its just the progress display not showing, just shows up when the progress is complete. And you yourself told me even if you reverted the changes, its not working. So its not a fault of my PR. ☺

**Comment by s0md3v** [comment]
I have found a fix.
I will make a commit in 10.

**Comment by s0md3v** [comment]
Phewwww :sleepy: 
We finally fixed it.
You can open another PR for the JS logic fix.

**Pull request merged**
