### PR TITLE
Update photon.py

### PR DESCRIPTION
**Pull request by mhcone**
use fake useragent replace the ua list

### CODE REVIEW

**Comment by s0md3v** [comment]
If you go through the [fake_useragent](https://github.com/hellysmile/fake-useragent/blob/master/fake_useragent/settings.py) library, you will see that it uses some external APIs to fetch user agents.
Photon is supposed to be as fast as possible so we can't afford an extra HTTP request just to fetch a random user agent.

**Comment by mhcone** [comment]
OK ,I get your point.
But I think that every request should use different user agent .
Maybe I can do this without third party library.

**Comment by s0md3v** [comment]
Don't bother. It will be done in next update anyway.

**Comment by mhcone** [comment]
OK, I am looking forward to it.

**Pull request closed without merging**
