### PR TITLE
Create `writer` function to demonstrate issue #32 (also added default output dir).

### PR DESCRIPTION
**Pull request by wzulfikar**

### CODE REVIEW

**Comment by wzulfikar** [comment]
I can confirm that the issue only affect python 3. original code doesn't have any issue when run using python 2.

**Comment by s0md3v** [comment]
Don't worry, I have resolved the issue will roll out the patch in 5.

**Comment by wzulfikar** [comment]
Alright thanks!

**Comment by wzulfikar** [comment]
Closing this :)

**Pull request closed without merging**
